@echo off
echo Instalacja zależności...
composer install

echo Generowanie klucza aplikacji...
php artisan key:generate

echo Migracje bazy danych...
php artisan migrate --seed

echo Uruchamianie lokalnego serwera...
php artisan serve
